name: Test
on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        entry:
          - { ruby: '2.6', mongodb: '4.4', gemfile: 'mongoid-5.0', bundler: '1.17.3' }
          - { ruby: '2.7', mongodb: '4.4', gemfile: 'mongoid-5.0', bundler: '1.17.3' }
          - { ruby: '2.7', mongodb: '4.4', gemfile: 'mongoid-6.0' }
          - { ruby: '2.7', mongodb: '4.4', gemfile: 'mongoid-7.0' }
          - { ruby: '3.1', mongodb: '4.4', gemfile: 'mongoid-8.0' }
          - { ruby: '3.1', mongodb: '4.4', gemfile: 'mongoid-8.1' }

    name: test (ruby=${{ matrix.entry.ruby }}, mongodb=${{ matrix.entry.mongodb }}), gemfile=${{ matrix.entry.gemfile }})

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.entry.gemfile }}.gemfile

    steps:
      - name: Set up MongoDB ${{ matrix.entry.mongodb }}
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.entry.mongodb }}
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
          bundler: '${{ matrix.entry.bundler || 1 }}'
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake

      - name: Code Climate
        if: ${{ env.CC_TEST_REPORTER_ID != '' && success() && matrix.coverage == 'true' }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
          chmod +x ./cc-test-reporter;
          ./cc-test-reporter before-build;
          ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json coverage/.resultset.json;
          ./cc-test-reporter upload-coverage;
