name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        entry:
          - { ruby: '2.6', mongodb: 'mongo:4.2', mongoid: '5.0', bundler: '1.17.3' }
          - { ruby: '2.7', mongodb: 'mongo:4.2', mongoid: '5.0', bundler: '1.17.3' }
          - { ruby: '2.7', mongodb: 'mongo:4.2', mongoid: '6.0' }
          - { ruby: '2.7', mongodb: 'mongo:4.2', mongoid: '7.0' }
          - { ruby: '3.1', mongodb: 'mongo:4.2', mongoid: '7.0' }

    name: test (ruby=${{ matrix.entry.ruby }}, mongodb=${{ matrix.entry.mongodb }}), mongoid=${{ matrix.entry.mongoid }})

    services:
      mongo:
        image: ${{ matrix.entry.mongodb }}
        ports: ['27017:27017']

    env:
      MONGOID_VERSION: ${{ matrix.entry.mongoid }}
      COVERAGE: ${{ matrix.coverage }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.entry.ruby }}
        bundler-cache: true

    - name: Checks
      if: ${{ matrix.coverage == 'true' }}
      run: |
        bundle exec rubocop
        # Disabled until mongoid-danger is updated to support Github Actions
        # bundle exec danger

    - name: Run tests
      run: bundle exec rspec

    - name: Code Climate
      if: ${{ env.CC_TEST_REPORTER_ID != '' && success() && matrix.coverage == 'true' }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
        chmod +x ./cc-test-reporter;
        ./cc-test-reporter before-build;
        ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json coverage/.resultset.json;
        ./cc-test-reporter upload-coverage;
